### PR TITLE
BEST PLS GIVE ME THIS

### PR DESCRIPTION
**Pull request by unlimitedcoder2**
i got tons nitros wtf

### CODE REVIEW

**Comment by JacobWennebro** [comment]
Sounds reasonable considering it's supposed to be a generator not a computer virus :)

**Review by IlmarsXd — APPROVED** [review]
amazing changes, must be merged. truly life changing

**Comment by TatoExp** [comment]
LGTM

**Comment by JacobWennebro** [comment]
I think the token stealer issue remains

**Pull request closed without merging**
